Repository NorwegianRefugeeCouncil/core, pull requests merged in 2022-11, with the labels that each got.

#54 UI Tweaks
  internal/api/individual.go
  internal/handlers/individuals.go
  web/templates/countries.gohtml
  web/templates/individuals.gohtml
  web/templates/nav.gohtml
  web/theme/theme.scss
Labels: approved, size/L

#48 COR-539 Generic Form Definition
  README.md
  internal/api/individual.go
  internal/handlers/individual.go
  internal/utils/pointers/pointers.go
  internal/validation/individual.go
  internal/views/individual_form.go
  pkg/views/forms/README.md
  pkg/views/forms/codec.go
  pkg/views/forms/codec_bool.go
  pkg/views/forms/codec_int.go
  pkg/views/forms/codec_str.go
  pkg/views/forms/codec_strlist.go
  pkg/views/forms/codec_time.go
  pkg/views/forms/field_input_checkbox.go
  pkg/views/forms/field_input_checkbox_test.go
  pkg/views/forms/field_input_date.go
  pkg/views/forms/field_input_date_test.go
  pkg/views/forms/field_input_hidden.go
  pkg/views/forms/field_input_hidden_test.go
  pkg/views/forms/field_input_id.go
  pkg/views/forms/field_input_id_test.go
  pkg/views/forms/field_input_number.go
  pkg/views/forms/field_input_number_test.go
  pkg/views/forms/field_input_select.go
  pkg/views/forms/field_input_select_test.go
  pkg/views/forms/field_input_text.go
  pkg/views/forms/field_input_text_test.go
  pkg/views/forms/field_input_textarea.go
  pkg/views/forms/field_input_textarea_test.go
  pkg/views/forms/field_kind.go
  pkg/views/forms/field_kind_test.go
  pkg/views/forms/form.gohtml
  pkg/views/forms/form_test.go
  pkg/views/forms/forms.go
  pkg/views/forms/interface.go
  pkg/views/forms/render.go
  pkg/views/forms/utils.go
  web/templates/individual.gohtml
  web/theme/theme.scss
Labels: approved, size/XXL

#63 Extract database batching logic
  internal/db/const.go
  internal/db/individual.go
  internal/db/utils.go
  internal/db/utils_test.go
Labels: approved, size/L

#53 COR-533-add-batch-delete-action
  internal/api/individual.go
  internal/db/individual.go
  internal/handlers/individuals_delete.go
  internal/server/routes.go
  web/templates/individuals.gohtml
Labels: approved, size/L

#60 Cor 558 filter all queries on country
  internal/db/individual.go
  internal/handlers/individual.go
  internal/handlers/individual_delete.go
  internal/handlers/individuals_delete.go
  internal/handlers/individuals_upload.go
  internal/handlers/utils.go
Labels: approved, size/M

#59 COR-512: offer template download
  web/static/nrc_grf_template.xlsx
  web/templates/nav.gohtml
Labels: approved, size/XS

#66 COR-566 highlight selected number of individuals to show
  web/templates/individuals.gohtml
Labels: approved, size/XS

#61 COR-558 - Prevent users from uploading non-existent ids
  internal/handlers/utils.go
Labels: approved, size/S

#69 Fix sonarcloud issues
  internal/server/middleware/utils_test.go
  pkg/api/validation/errors.go
  pkg/api/validation/errors_test.go
  pkg/views/forms/form_test.go
  web/theme/theme.scss
Labels: approved, size/L

#65 COR-565 pointer cursor on individual record count
  internal/api/individual.go
  web/templates/individuals.gohtml
Labels: approved, size/S, do-not-merge/contains-merge-commits

#70 Table-alignment
  web/templates/individuals.gohtml
Labels: size/XL, approved

#77 COR-579 Add displacement status type
  internal/api/displacement_status.go
  internal/api/displacement_status_test.go
Labels: approved, size/L

#76 Cor 578 add gender type
  internal/api/gender.go
  internal/api/gender_test.go
Labels: approved, size/L

#74 COR-576 add list of iso countries
  internal/constants/countries.go
  internal/constants/countries.json
Labels: approved, size/XXL

#75 COR-577 add ISO 639-3 language data
  internal/constants/language_macro_mapping.json
  internal/constants/language_names.json
  internal/constants/language_retirements.json
  internal/constants/languages.go
  internal/constants/languages.json
Labels: approved, size/XXL

#72 Batch logic
  internal/db/individual.go
  internal/db/utils.go
  internal/db/utils_test.go
Labels: approved, size/M

#73 Fix filtering individuals by id
  internal/constants/individual.go
  internal/handlers/individuals.go
  web/templates/individuals.gohtml
Labels: approved, size/S, do-not-merge/contains-merge-commits

#67 COR-567 disable pagination buttons when appropriate
  web/templates/individuals.gohtml
Labels: approved, size/S, do-not-merge/contains-merge-commits

#78 COR-580 add disability level type
  internal/api/disability_level.go
  internal/api/disability_level_test.go
Labels: approved, size/L

#79 COR-582 add constants for new fields
  internal/constants/individual.go
  internal/handlers/individuals.go
Labels: size/XL, approved

#80 COR-583 rename GetAllOptions
  internal/api/individual.go
  internal/api/individual_list_options.go
  internal/api/validation/list_individuals_options.go
  internal/api/validation/list_individuals_options_test.go
  internal/db/individual.go
  internal/db/individual_mock.go
  internal/handlers/individuals.go
  internal/handlers/individuals_delete.go
  internal/handlers/individuals_download.go
  internal/handlers/individuals_upload.go
Labels: approved, size/L

#58 COR-535: make first two columns sticky and table scroll horizontally
  web/templates/individuals.gohtml
  web/theme/theme.scss
Labels: approved, size/L

#81 COR-584 use constants for ListIndividualsOptions
  internal/api/individual_list_options.go
  internal/api/individual_list_options_decoder.go
  internal/api/individual_list_options_encoder.go
  internal/api/individual_list_options_test.go
  internal/constants/individual.go
  internal/handlers/individuals.go
  internal/handlers/individuals_download.go
  web/templates/individuals.gohtml
Labels: size/XL, approved

#71 Fix sonarcloud issues
  internal/db/individual.go
  internal/db/sql_individual_list.go
  internal/db/sql_individual_list_test.go
Labels: approved, size/L, do-not-merge/contains-merge-commits

#82 COR-585 use new types
  internal/api/disability_level.go
  internal/api/displacement_status.go
  internal/api/gender.go
  internal/api/individual.go
  internal/api/individual_list_options.go
  internal/api/individual_list_options_decoder.go
  internal/api/individual_list_options_encoder.go
  internal/api/individual_list_options_test.go
  internal/api/individual_tabular.go
  internal/api/individual_tabular_test.go
  internal/api/validation/const.go
  internal/api/validation/individual.go
  internal/api/validation/individual_test.go
  internal/api/validation/list_individuals_options.go
  internal/api/validation/list_individuals_options_test.go
  internal/constants/individual.go
  internal/containers/set.go
  internal/db/individual.go
  internal/db/sql_individual_list.go
  internal/db/sql_individual_list_test.go
  internal/handlers/individual.go
  internal/handlers/individuals_delete.go
  internal/handlers/individuals_upload.go
  internal/handlers/utils.go
  internal/server/routes.go
  internal/views/individual_form.go
  pkg/logutils/escape.go
  web/templates/individuals.gohtml
Labels: size/XL, approved

#86 Fix roboto font
  web/templates/base.gohtml
  web/theme/theme.scss
Labels: approved, size/XS

#84 COR-568 add fields to list view
  deploy/docker-compose.yaml
  internal/api/disability_level.go
  internal/api/displacement_status.go
  internal/api/gender.go
  internal/api/validation/const.go
  internal/api/validation/individual.go
  internal/server/templates.go
  internal/views/individual_form.go
  web/templates/individuals.gohtml
  web/theme/theme.scss
Labels: approved, size/L, do-not-merge/contains-merge-commits

#83 COR-581 individual form
  .idea/csv-plugin.xml
  cmd/mockdata/main.go
  deploy/docker-compose.yaml
  go.mod
  go.sum
  internal/api/disability_level.go
  internal/api/displacement_status.go
  internal/api/displacement_status_test.go
  internal/api/gender.go
  internal/api/individual.go
  internal/api/individual_tabular.go
  internal/api/individual_tabular_test.go
  internal/api/validation/const.go
  internal/api/validation/individual.go
  internal/api/validation/individual_test.go
  internal/constants/individual.go
  internal/db/country.go
  internal/db/db.go
  internal/db/individual.go
  internal/db/migrations.go
  internal/db/migrations/postgres/012_new_individual.up.sql
  internal/db/sql_individual_list.go
  internal/db/sql_individual_list_test.go
  internal/handlers/individual.go
  internal/server/templates.go
  internal/views/individual_form.go
  pkg/views/forms/form.gohtml
  pkg/views/forms/forms.go
  web/static/nrc_grf_template.xlsx
  web/templates/individuals.gohtml
  web/theme/theme.scss
Labels: approved, size/XXL

#94 COR-571 apply list options to database query
  internal/db/sql_individual_list.go
  internal/db/sql_individual_list_test.go
Labels: size/XL, approved

#92 COR-573 encode individual list options to URL
  internal/api/individual_list_options.go
  internal/api/individual_list_options_decoder.go
  internal/api/individual_list_options_encoder.go
  internal/api/individual_list_options_test.go
  internal/constants/individual.go
  internal/db/sql_individual_list.go
  internal/db/sql_individual_list_test.go
Labels: approved, size/XXL

#95 COR-590: approximate mock up designs for country selection
  web/templates/nav.gohtml
  web/theme/theme.scss
Labels: approved, size/S

#96 COR-523 sorting
  internal/api/individual_list_options.go
  internal/api/individual_list_options_decoder.go
  internal/api/individual_list_options_encoder.go
  internal/api/individual_list_options_test.go
  internal/constants/individual.go
  internal/db/sql_individual_list.go
  internal/db/sql_individual_list_test.go
  internal/handlers/individuals.go
  web/templates/individuals.gohtml
  web/theme/theme.scss
Labels: approved, size/XXL

#101 Update individual_tabular.go
  internal/api/individual_tabular.go
Labels: approved, size/S

#99 Validate max length
  internal/api/validation/country_test.go
  internal/api/validation/individual.go
  internal/api/validation/individual_test.go
Labels: size/XL, approved

#97 Restore table scroll position
  web/templates/individuals.gohtml
Labels: approved, size/S

#102 COR-608: fix download
  internal/api/individual_tabular.go
  internal/constants/individual.go
  web/templates/individuals.gohtml
  web/templates/nav.gohtml
Labels: approved, size/M, do-not-merge/contains-merge-commits

#98 COR-600: fix single individual deletion
  web/templates/individual.gohtml
Labels: approved, size/S

#105 COR-653 add form alerts
  internal/handlers/individual.go
  pkg/views/alert/alert.go
  pkg/views/bootstrap/style.go
  web/templates/individual.gohtml
  web/theme/theme.scss
Labels: approved, size/L

#106 COR-589: move search form to navbar
  web/templates/base.gohtml
  web/templates/individuals.gohtml
  web/templates/nav.gohtml
  web/templates/searchForm.gohtml
Labels: size/XL, approved
