Repository NorwegianRefugeeCouncil/core, pull requests merged in 2022-10, with the labels that each got.

#4 COR-502 Add country select frontend
  .gitignore
  web/templates/layout.gohtml
Labels: approved, lgtm, size/M

#9 Add terraform manifest
  azure-pipelines.yml
  deploy/terraform/.gitignore
  deploy/terraform/azurerm_linux_web_app.app.tf
  deploy/terraform/azurerm_postgresql_flexible_server.postgres.tf
  deploy/terraform/azurerm_postgresql_flexible_server_database.db.tf
  deploy/terraform/azurerm_private_dns_zone.postgres_dns.tf
  deploy/terraform/azurerm_private_dns_zone_virtual_network_link.vnet_link.tf
  deploy/terraform/azurerm_resource_group.rg.tf
  deploy/terraform/azurerm_role_assignment.acr_pull.tf
  deploy/terraform/azurerm_service_plan.plan.tf
  deploy/terraform/azurerm_subnet.postgres_subnet.tf
  deploy/terraform/azurerm_subnet.runtime_subnet.tf
  deploy/terraform/azurerm_user_assigned_identity.app.tf
  deploy/terraform/azurerm_virtual_network.vnet.tf
  deploy/terraform/data.azurerm_container_registry.acr.tf
  deploy/terraform/main.tf
  deploy/terraform/random_id.app_id.tf
  deploy/terraform/random_id.postgresql_id.tf
  deploy/terraform/random_password.postgres_admin_password.tf
  deploy/terraform/random_pet.postgres_admin_username.tf
  deploy/terraform/variables.tf
Labels: approved, size/L

#5 COR-502 Single country per Individual + Cleanup
  Makefile
  deploy/envoy.yaml
  internal/api/individual.go
  internal/api/user_country.go
  internal/auth/permissions.go
  internal/db/individual.go
  internal/db/migrations.go
  internal/db/migrations/postgres/008_individual_country.up.sql
  internal/db/permissions.go
  internal/handlers/const.go
  internal/handlers/countries.go
  internal/handlers/country.go
  internal/handlers/country_select.go
  internal/handlers/country_selector.go
  internal/handlers/individual.go
  internal/handlers/individuals.go
  internal/handlers/individuals_download.go
  internal/handlers/individuals_upload.go
  internal/handlers/templates.go
  internal/handlers/user.go
  internal/handlers/users.go
  internal/handlers/utils.go
  internal/server/middleware_countries.go
  internal/server/middleware_ensure_selected_country.go
  internal/server/middleware_global_admin.go
  internal/server/middleware_jwt.go
  internal/server/middleware_permissions.go
  internal/server/middleware_selected_country.go
  internal/server/routes.go
  internal/utils/context.go
  scripts/find-compose.sh
  scripts/prerequisites.sh
  web/templates/countries.gohtml
  web/templates/country_select.gohtml
  web/templates/index.gohtml
  web/templates/individual.gohtml
  web/templates/individuals.gohtml
  web/templates/layout.gohtml
  web/templates/user.gohtml
Labels: approved, size/XXL

#8 COR-508 Enhance dockerfile with multi-stage builds
  .gitignore
  Makefile
  build/package/app.Dockerfile
  build/package/app.Dockerfile.dockerignore
  scripts/docker-dev-coverage.sh
  scripts/docker-dev-entrypoint.sh
  scripts/docker-dev-tests.sh
Labels: approved, size/L

#11 Cor 518 add theming to docker build
  build/package/app.Dockerfile
Labels: approved, size/XS

#7 COR-503 Use okta groups for permissions
  .idea/runConfigurations/serve__postgres_.xml
  Makefile
  cmd/serve.go
  deploy/docker-compose.yaml
  deploy/envoy.yaml
  deploy/oidc-config.json
  deploy/oidc-users.json
  internal/api/country.go
  internal/api/user.go
  internal/api/user_country.go
  internal/auth/permissions.go
  internal/db/country.go
  internal/db/migrations.go
  internal/db/migrations/postgres/009_remove_permissions.up.sql
  internal/db/migrations/postgres/010_country_jwt_group.up.sql
  internal/db/permissions.go
  internal/db/user.go
  internal/handlers/country.go
  internal/handlers/country_select.go
  internal/handlers/country_selector.go
  internal/handlers/individual.go
  internal/handlers/individuals_upload.go
  internal/handlers/user.go
  internal/handlers/users.go
  internal/server/middleware_global_admin.go
  internal/server/middleware_jwt.go
  internal/server/middleware_jwt_test.go
  internal/server/middleware_permissions.go
  internal/server/middleware_permissions_test.go
  internal/server/routes.go
  internal/server/server.go
  web/templates/country.gohtml
  web/templates/layout.gohtml
  web/templates/user.gohtml
  web/templates/users.gohtml
Labels: approved, lgtm, size/XXL

#13 COR-508 Add validation to server options
  internal/server/options.go
  internal/server/options_test.go
  internal/server/server.go
Labels: approved, lgtm, size/L

#15 COR-508 Allow JWT based authentication
  .idea/runConfigurations/serve__postgres_.xml
  Makefile
  cmd/serve.go
  deploy/envoy.yaml
  deploy/terraform/azurerm_linux_web_app.app.tf
  go.mod
  go.sum
  internal/server/middleware_auth.go
  internal/server/middleware_auth_test.go
  internal/server/middleware_jwt.go
  internal/server/middleware_jwt_test.go
  internal/server/options.go
  internal/server/options_test.go
  internal/server/routes.go
  internal/server/server.go
Labels: size/XL, approved, lgtm

#12 COR-514-csv-cleanup
  internal/api/individual.go
  internal/api/individual_csv.go
  internal/api/utils.go
  internal/constants/individual.go
  internal/db/individual.go
  internal/handlers/const.go
  internal/handlers/individual.go
  internal/handlers/individuals.go
  internal/handlers/individuals_download.go
  internal/handlers/individuals_upload.go
  internal/handlers/templates.go
  internal/handlers/templates_test.go
  internal/utils/utils.go
  internal/validation/errors.go
  internal/validation/individual.go
Labels: size/XL, approved

#14 COR-510: nrc styling
  internal/handlers/index.go
  internal/server/routes.go
  internal/server/templates.go
  web/static/favicon.ico
  web/templates/base.gohtml
  web/templates/countries.gohtml
  web/templates/country.gohtml
  web/templates/country_select.gohtml
  web/templates/home.gohtml
  web/templates/individual.gohtml
  web/templates/individuals.gohtml
  web/templates/nav.gohtml
  web/theme/theme.scss
Labels: size/XL, approved

#18 COR-508 proper jwt authentication
  .idea/runConfigurations/serve__postgres_.xml
  Makefile
  cmd/serve.go
  deploy/envoy.yaml
  deploy/terraform/azurerm_linux_web_app.app.tf
  deploy/terraform/variables.tf
  go.mod
  go.sum
  internal/server/middleware_auth.go
  internal/server/middleware_auth_test.go
  internal/server/options.go
  internal/server/options_test.go
  internal/server/routes.go
  internal/server/server.go
Labels: approved, size/XXL

#20 Cor 502 Fix individual upload country_id
  internal/handlers/individuals_upload.go
Labels: approved, size/S, lgtm

#21 COR-508 add gzip compression support
  go.mod
  go.sum
  internal/server/routes.go
Labels: approved, size/S, lgtm

#16 COR-514-excel-upload
  .gitignore
  examples/bla.xlsx
  go.mod
  go.sum
  internal/api/individual_tabular.go
  internal/api/individual_tabular_test.go
  internal/constants/individual.go
  internal/handlers/individuals_upload.go
  web/templates/individuals.gohtml
Labels: approved, size/L

#22 Individual generator upgrades
  cmd/mockData.go
  cmd/mockdata/main.go
  internal/db/individual.go
Labels: approved, size/M

#17 COR-502 Allow users to share individual list links
  Makefile
  go.mod
  go.sum
  internal/auth/interface.go
  internal/auth/interface_mock.go
  internal/db/individual.go
  internal/db/individual_mock.go
  internal/handlers/individuals.go
  internal/handlers/individuals_test.go
  internal/handlers/templates.go
  internal/server/routes.go
  main.go
  tools/tools.go
  web/templates/individuals.gohtml
  web/templates/nav.gohtml
Labels: size/XL, approved

#19 Cor 508 session refresh
  .idea/runConfigurations/serve__postgres_.xml
  Makefile
  cmd/serve.go
  deploy/terraform/azurerm_linux_web_app.app.tf
  internal/api/user.go
  internal/auth/session.go
  internal/handlers/templates.go
  internal/logging/const.go
  internal/server/middleware_auth.go
  internal/server/middleware_permissions.go
  internal/server/options.go
  internal/server/options_test.go
  internal/server/server.go
  internal/server/templates.go
  internal/server/templates_time.go
  internal/utils/context.go
  web/templates/base.gohtml
Labels: approved, size/L

#25 COR-508 Goland deployment script fix
  .idea/runConfigurations/serve__postgres_.xml
Labels: approved, lgtm, size/XS

#29 COR-515 excel download
  internal/api/individual.go
  internal/api/individual_tabular.go
  internal/api/individual_tabular_test.go
  internal/constants/individual.go
  internal/handlers/individual.go
  internal/handlers/individuals_download.go
  web/templates/individuals.gohtml
Labels: approved, lgtm, size/L

#28 Add some wip docs for changing the form's fields
  README.md
Labels: approved, lgtm, size/M

#27 COR-508 Add better documentation to serve command
  cmd/serve.go
Labels: approved, lgtm, size/L

#30 Cor 502 token expiration handling
  .idea/runConfigurations/serve__postgres_.xml
  Makefile
  cmd/serve.go
  deploy/terraform/azurerm_linux_web_app.app.tf
  internal/handlers/session.go
  internal/server/middleware_auth.go
  internal/server/options.go
  internal/server/options_test.go
  internal/server/routes.go
  internal/server/server.go
  web/templates/base.gohtml
Labels: approved, lgtm, size/L

#26 COR-510: ui fixes
  web/templates/nav.gohtml
  web/theme/theme.scss
Labels: approved, size/L

#32 COR-519: UX Fixes
  internal/api/individual.go
  internal/handlers/index.go
  web/templates/countries.gohtml
  web/templates/country.gohtml
  web/templates/country_select.gohtml
  web/templates/individual.gohtml
  web/templates/individuals.gohtml
  web/templates/nav.gohtml
  web/theme/theme.scss
Labels: size/XL, approved

#35 Ensure jwt group match is case sensitive
  internal/server/middleware_permissions.go
Labels: approved, size/XS

#36 Add easy to remember fake users
  deploy/oidc-users.json
Labels: approved, size/M

#37 Revert change to isMinor filter check
  internal/api/individual.go
Labels: approved, size/XS

#40 Move middleware to a sub package
  cmd/serve.go
  internal/server/middleware/auth.go
  internal/server/middleware/auth_test.go
  internal/server/middleware/countries.go
  internal/server/middleware/ensure_selected_country.go
  internal/server/middleware/has_country_permission.go
  internal/server/middleware/has_global_admin_permission.go
  internal/server/middleware/logging.go
  internal/server/middleware/permissions.go
  internal/server/middleware/permissions_test.go
  internal/server/middleware/request_id.go
  internal/server/middleware/selected_country.go
  internal/server/options.go
  internal/server/options_test.go
  internal/server/routes.go
  internal/server/server.go
Labels: approved, size/L

#24 COR-508 Fix performance issues when uploading large csvs
  internal/db/individual.go
  internal/handlers/individuals_upload.go
  internal/utils/utils.go
Labels: approved, lgtm, size/L

#33 COR-504 fix token refresh
  .idea/runConfigurations/serve__postgres_.xml
  Makefile
  cmd/serve.go
  deploy/terraform/azurerm_linux_web_app.app.tf
  internal/handlers/session.go
  internal/server/options.go
  internal/server/options_test.go
  internal/server/routes.go
  internal/server/server.go
  internal/server/templates.go
  web/templates/base.gohtml
Labels: approved, size/L

#38 COR-525 allow deleting single individual
  deploy/docker-compose.yaml
  internal/api/individual.go
  internal/constants/individual.go
  internal/db/individual.go
  internal/db/individual_mock.go
  internal/db/migrations.go
  internal/db/migrations/postgres/011_individual_soft_delete.up.sql
  internal/handlers/individual_delete.go
  internal/server/routes.go
  web/templates/individual.gohtml
Labels: approved, size/L, do-not-merge/contains-merge-commits

#39 Country path parameter
  cmd/serve.go
  internal/auth/interface.go
  internal/handlers/countries.go
  internal/handlers/country.go
  internal/handlers/country_select.go
  internal/handlers/country_selector.go
  internal/handlers/index.go
  internal/handlers/individual.go
  internal/handlers/individual_delete.go
  internal/handlers/individuals.go
  internal/handlers/individuals_download.go
  internal/handlers/individuals_test.go
  internal/handlers/individuals_upload.go
  internal/server/middleware/auth.go
  internal/server/middleware/auth_test.go
  internal/server/middleware/countries.go
  internal/server/middleware/ensure_selected_country.go
  internal/server/middleware/has_country_permission.go
  internal/server/middleware/has_country_permission_test.go
  internal/server/middleware/has_global_admin_permission.go
  internal/server/middleware/has_global_admin_permission_test.go
  internal/server/middleware/logging.go
  internal/server/middleware/permissions.go
  internal/server/middleware/permissions_test.go
  internal/server/middleware/request_id.go
  internal/server/middleware/selected_country.go
  internal/server/middleware/utils_test.go
  internal/server/options.go
  internal/server/options_test.go
  internal/server/routes.go
  internal/server/server.go
  web/templates/countries.gohtml
  web/templates/country_select.gohtml
  web/templates/home.gohtml
  web/templates/individual.gohtml
  web/templates/individuals.gohtml
  web/templates/nav.gohtml
Labels: approved, size/XXL

#51 Ui-tweaks
  internal/handlers/individual_delete.go
  web/static/nrc_logo.png
  web/templates/countries.gohtml
  web/templates/country.gohtml
  web/templates/individual.gohtml
  web/templates/individuals.gohtml
  web/templates/nav.gohtml
  web/theme/theme.scss
Labels: approved, size/L

#52 Add checkboxes with configurable action to table
  web/templates/individuals.gohtml
Labels: approved, size/M

#49 Let the repo take care of the (created/updated/deleted)At fields
  internal/db/individual.go
Labels: approved, size/XS

#56 Fix individual generator
  cmd/mockData.go
  cmd/mockdata/main.go
Labels: approved, size/S

#50 Properly display anonymous individuals in table
  web/templates/individuals.gohtml
Labels: approved, size/S
